# Configuration file for Flamenco.
# For an explanation of the fields, refer to flamenco-manager-example.yaml
#
# NOTE: this file will be overwritten by Flamenco Manager's web-based configuration system.
#
# This file was written on 2024-04-12 16:32:29 +02:00 by Flamenco 3.4

_meta:
  version: 3
manager_name: Flamenco
database: flamenco-manager.sqlite
database_check_period: 1h0m0s
listen: :12055
autodiscoverable: true
local_manager_storage_path: ./flamenco-manager-storage
shared_storage_path: "/flamenco"
shaman:
  enabled: true
  garbageCollect:
    period: 24h0m0s
    maxAge: 744h0m0s
    extraCheckoutPaths: []
task_timeout: 10m0s
worker_timeout: 1m0s
blocklist_threshold: 3
task_fail_after_softfail_count: 3
mqtt:
  client:
    broker: ""
    clientID: flamenco
    topic_prefix: flamenco
    username: ""
    password: ""
variables:
  blender:
    values:
    - platform: linux
      value: blender
    - platform: windows
      value: blender
    - platform: darwin
      value: blender
  blenderArgs:
    values:
    - platform: all
      value: -b -y
  clientStoragePath:
    values:
      - platform: linux
        value: /flamenco
      - platform: windows
        value: "Y:/flamenco"
  jobSubPath:
    values:
    - platform: all
      value: jobs
  renderSubPath:
    values:
    - platform: all
      value: render
  deviceType:
    values:
    - platform: all
      value: "OPTIX"